apiVersion: v1

kind: Service

metadata:
  name: nginx-service
  
spec:
  type: NodePort
  selector:
    app: server-app
    
  ports:
    - protocol: TCP
	    port: 443
      targetPort: 443
      NodePort: 30000
