apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-deployment
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-app
  
  template:
    metadata:
      labels:
        app: server-app
    
    spec:
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
